blank_issues_enabled: false
contact_links:
  - name: qbuildr.new related issues
    url: https://github.com/qbuildr/qbuildr.new/issues/new/choose
    about: Report issues related to qbuildr.new (not qbuildr.diy)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other qbuildr.diy users.
